# Generated by Django 4.1.2 on 2023-01-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_alter_profile_profileimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('creation_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('key_issue', models.CharField(max_length=2000)),
                ('Birth_year', models.IntegerField()),
                ('zip_code', models.IntegerField()),
                ('engagement_score', models.IntegerField()),
            ],
        ),
    ]
