# Generated by Django 4.1.2 on 2023-01-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Birth_year',
            field=models.IntegerField(default=1994),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default='john@g.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='engagement_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='key_issue',
            field=models.CharField(default='Det her betyder noget for mig', max_length=2000),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(default='john', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(default=22222222),
        ),
        migrations.AlterField(
            model_name='member',
            name='zip_code',
            field=models.IntegerField(default=2100),
        ),
    ]
