# Generated by Django 4.1.2 on 2023-01-12 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_member_birth_year_alter_member_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='creation_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
