# Generated by Django 4.1.2 on 2023-01-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_member_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Birth_year',
            new_name='birth_year',
        ),
    ]
