# Generated by Django 4.1.2 on 2023-01-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_birth_year_member_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='key_issue',
            field=models.CharField(default='Det her betyder noget for mig', max_length=4000),
        ),
    ]
