# Generated by Django 4.1.2 on 2023-01-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_member_key_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='hash_value',
            field=models.IntegerField(default=100),
        ),
    ]
