# Generated by Django 4.1.2 on 2023-01-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_member_hash_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='hash_value',
        ),
        migrations.AddField(
            model_name='member',
            name='auto_id',
            field=models.CharField(default='id', max_length=100),
        ),
    ]
