# Generated by Django 4.1.2 on 2023-01-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_member_hash_value_member_auto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='key_issue',
            field=models.CharField(default='Det her betyder noget for mig', max_length=6000),
        ),
    ]
