# Generated by Django 4.1.2 on 2023-01-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_member_key_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='key_issue',
            field=models.CharField(default='Det her betyder noget for mig', max_length=10000),
        ),
    ]
